<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relacion [
<!ELEMENT relacion (persona)+>
<!ELEMENT persona (nombre,email*,parentesco?)>
<!ATTLIST persona carnet ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT parentesco EMPTY>
<!ATTLIST parentesco tutor-legal IDREFS #IMPLIED hermano-a IDREFS #IMPLIED>
]>

<relacion>
  <persona carnet="SI">
    <nombre>
    </nombre>
    <email>
    </email>
    <parentesco>
    </parentesco>
  </persona>
</relacion>


